apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack-notification
  namespace: cattle-monitoring-system
  labels:
    alertmanagerconfig: slack
spec:
  route:
    groupBy: ['namespace','alertname']        ##
    groupWait: 30s          ## 기본값 30초로 / 그룹의 초기 대기 시간
    groupInterval: 5m       ## 기본값 5분 /  그룹의 알람 기간 간격
    repeatInterval: 12h     ## 기본값 4시간 / 해결되지 않은 알람 재전송 기간 간격
    receiver: slack-notification
    routes:
    - matchers:
      - matchType: =
        name: severity
        value: none
  receivers:
  - name: slack-notification
    slackConfigs:
    - sendResolved: true
      apiURL:
        name: slack-webhook
        key: slack_webhook_url