apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack-notification
  namespace: cattle-monitoring-system
  labels:
    alertmanagerconfig: slack
spec:
  route:
    receiver: slack-notification
  receivers:
  - name: slack-notification
    slackConfigs:
    - sendResolved: true
      apiURL: 'https://hooks.slack.com/services/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'