apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack-notification
  namespace: cattle-monitoring-system
spec:
  route:
    groupBy: ['namespace']        ##
    groupWait: 30s          ## 기본값 30초로 / 그룹의 초기 대기 시간
    groupInterval: 3m       ## 기본값 5분 /  그룹의 알람 기간 간격
    repeatInterval: 3m     ## 기본값 4시간 / 해결되지 않은 알람 재전송 기간 간격
    receiver: slack-notification
    matchers:
      - matchType: '='
        name: severity
        value: none
      - matchType: '='
        name: severity
        value: warning
      - matchType: '='
        name: severity
        value: critical
  receivers:
  - name: slack-notification
    slackConfigs:
    - sendResolved: true
      apiURL: 'https://hooks.slack.com/services/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'