apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ping
  namespace: ping
  labels:
    Tier: app
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      Tier: app
  template:
    metadata:
      labels:
        Tier: app
    spec:
      nodeSelector:
        tier: ng
        role: game
      tolerations:
      - key: ng
        operator: Equal
        value: game
        effect: NoSchedule
      containers:
      - name: test
        image: "{{ .Values.image.repository }}:{{ .Values.image.test_tag }}"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: {{ .Values.containerPort }}
          protocol: TCP
        readinessProbe:
          httpGet:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ping
  namespace: ping
  labels:
    Tier: service
spec:
  selector:
    Tier: app
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}
  type: ClusterIP