apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  namespace: test
  labels:
    Tier: app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      Tier: app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        Tier: app
    spec:
      serviceAccountName: test-sa	
      containers:
      - name: test
        image: amazon/aws-cli
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent



