apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deploy-1
  labels:
    app: test-app-1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: test-app-1
  template:
    metadata:
      labels:
        app: test-app-1
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: game-ng
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                - game-ng
      containers:
        - name: apache
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          resources: 
{{ toYaml .Values.apache.resources | indent 12 }}
          volumeMounts:
            name: test-volume
          - mountPath: /testW
      volumes:
      - name: test-volume
        hostPath:
          path: /test




