apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  namespace: test
  labels:
    Tier: app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      Tier: app
  template:
    metadata:
      labels:
        Tier: app
    spec:
      containers:
      - name: test
        image: "{{ .Values.image.repository }}:{{ .Values.image.test_tag }}"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: {{ .Values.containerPort }}
          protocol: TCP
      envFrom:
        - configMapRef:
            name: test-config




