apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  namespace: test
  labels:
    Tier: app
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
  selector:
    matchLabels:
      Tier: app
  template:
    metadata:
      labels:
        Tier: app
    spec:
      nodeSelector:
        tier: ng
        role: game
      tolerations:
      - key: ng
        operator: Equal
        value: game
        effect: NoSchedule
      containers:
      - name: test
        image: "{{ .Values.image.repository }}:{{ .Values.image.test_tag }}"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: {{ .Values.containerPort }}
          protocol: TCP
        env:
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        # envFrom:
        #   - configMapRef:
        #       name: test-config
        resources:
{{ toYaml .Values.image.resources | indent 12 }}
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        readinessProbe:
          httpGet:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      # You set volumes at the Pod level, then mount them into containers inside that Pod
      - name: config
        configMap:
          # Provide the name of the ConfigMap you want to mount.
          name: test-config
          items:
          - key: username
            path: test/user