apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-webhook
  namespace: cattle-monitoring-system
stringData:
  slack_webhook_url: "https://hooks.slack.com/services/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"