apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-webhook
  namespace: cattle-monitoring-system
stringData:
  slack_webhook_url: "https://hooks.slack.com/services/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"