apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-webhook
  namespace: cattle-monitoring-system
data:
  slack_webhook_url: "aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA1MjlOSDRGTE4vQjA2Rzc4MTJXOE4vZGZnUW9qMDVIVXVHYmlUQ0NyMG5VV2xaCg=="
  