apiVersion: v1
kind: Service
metadata:
  name: apahce-service
  namespace: test
  labels:
    Tier: service
spec:
  selector:
    Tier: app
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}
  type: NodePort