apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy-ver2
  namespace: test
  labels:
    Tier: app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      Tier: app
  template:
    metadata:
      labels:
        Tier: app
    spec:
      # serviceAccountName: test
      containers:
      - name: test
        image: "{{ .Values.test.repository }}:{{ .Values.test.test_tag }}"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: {{ .Values.containerPort }}
          protocol: TCP
        env:
          - name: Iamge_Tag
            value: {{ .Values.test.test_tag }}
        # envFrom:
        #   - configMapRef:
        #       name: test-config
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
      # You set volumes at the Pod level, then mount them into containers inside that Pod
      - name: config
        configMap:
          # Provide the name of the ConfigMap you want to mount.
          name: test-config
          items:
          - key: username
            path: test/user


