apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ClusterRoleBinding
subjects:
- kind: ServiceAccount
  name: test
  namespace: test
roleRef:
  kind: ClusterRole
  name: ClusterRole
  apiGroup: rbac.authorization.k8s.io