# Default values for test-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: 827398730268.dkr.ecr.ap-southeast-3.amazonaws.com/sy_kim_test
  # pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "20230912.060852"

apache:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

containerPort: 80

service:
  type: LoadBalancer 
  port: 80

