# Default values for test-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3

image:
  repository: 827398730268.dkr.ecr.ap-southeast-3.amazonaws.com/nv_dev_front
  test_tag: nv_dev_front-20231114.080441

test:
  repository: 827398730268.dkr.ecr.ap-southeast-3.amazonaws.com/nv_dev_front
  test_tag: nv_dev_front-20231114.045800


test:
  resources:
    limits:
      cpu: 50m
      memory: 10Mi
    requests:
      cpu: 50m
      memory: 10Mi

containerPort: 80

service:
  type: LoadBalancer 
  port: 80

