# Default values for test-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 10

image:
  repository: 827398730268.dkr.ecr.ap-southeast-3.amazonaws.com/nv_dev_front
  test_tag: nv_dev_front-20231114.045800
  resources:
    requests:
      memory: "1.5Gi"

test:
  repository: 827398730268.dkr.ecr.ap-southeast-3.amazonaws.com/nv_dev_front
  test_tag: nv_dev_front-20231114.045800


containerPort: 80

service:
  type: LoadBalancer 
  port: 80

