apiVersion: v1
kind: ConfigMap
metadata:
  name: escalator-config
  namespace: kube-system
data:
  nodegroups_config.yaml: |
    node_groups:
      - name: "mgmt-ng"
        label_key: "eks.amazonaws.com/nodegroup"
        label_value: "mgmt-ng"
        cloud_provider_group_name: "eks-mgmt-ng-dcc54149-777d-2437-4008-48978169263b"
        min_nodes: 2
        max_nodes: 5
        dry_mode: false
        taint_upper_capacity_threshold_percent: 30
        taint_lower_capacity_threshold_percent: 10
        slow_node_removal_rate: 1
        fast_node_removal_rate: 1
        scale_up_threshold_percent: 40
        scale_up_cool_down_period: 1m
        scale_up_cool_down_timeout: 5m
        soft_delete_grace_period: 1m
        hard_delete_grace_period: 5m
        taint_effect: "NoSchedule"
