apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: karpenter-podmonitor
  namespace: karpenter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: karpenter
      app.kubernetes.io/instance: karpenter
  podMetricsEndpoints:
  - port: http-metrics
    path: /metrics
  namespaceSelector:
    matchNames:
      - karpenter