apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deploy-2
  labels:
    app: test-app-2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: test-app-2
  template:
    metadata:
      labels:
        app: test-app-2
    spec:
      containers:
        - name: apache
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP


