apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: game-provisioner
spec:
  providerRef:
    name: game-template
  taints:
    - key: ng
      value: game
      effect: NoSchedule
  labels:
    tier: Provisioner
    role: game
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["t3.large"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: topology.kubernetes.io/zone
      operator: In
      values: ["ap-southeast-3a", "ap-southeast-3c"]
    - key: kubernetes.io/os
      operator: In
      values: ["linux"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]

  # Enables consolidation which attempts to reduce cluster cost by both removing un-needed nodes and down-sizing those
  # that can't be removed.  Mutually exclusive with the ttlSecondsAfterEmpty parameter.
  # consolidation:
  #   enabled: true

  # If omitted, the feature is disabled and nodes will never expire.  If set to less time than it requires for a node
  # to become ready, the node may expire before any pods successfully start.
  # ttlSecondsUntilExpired: 2592000 # 30 Days = 60 * 60 * 24 * 30 Seconds;

  # If omitted, the feature is disabled, nodes will never scale down due to low utilization
  ttlSecondsAfterEmpty: 30
