apiVersion: v1
kind: Service
metadata:
  name: test2
  namespace: test
  labels:
    tier: backend
    role: test2
spec:
  selector:
    tier: app
    role: test2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

